---
desired_state: present
debug: false
# Database defaults
# db_namespace: needs to be defined
db_cpu_limit: '0.5'
db_memory_limit: '0.5Gi'
db_cpu_request: '0.5'
db_memory_request: '0.5Gi'
db_storage: '20Gi'
db_storage_class: local-path
db_client: 'python'  # cli, .net, java, and more.

# Database version defaults postgres example
db_version: 15.7.0
mysql_version: 8.0.33
# For switchover
db_instance: pg-cluster-postgresql-0
db_candidate: pg-cluster-postgresql-1

# KubeBlocks
# crd_url: 'https://github.com/apecloud/kubeblocks/releases/download/v1.0.1/kubeblocks_crds.yaml'
helm_upstream_repo_url: 'https://apecloud.github.io/helm-charts'
kubeblocks_cache: /tmp/kubeblocks_cache
# you can mirror the above
helm_repo_url: 'https://apecloud.github.io/helm-charts'
helm_binary: /usr/bin/helm
# default addons have enabled set to false
kubeblocks_addons:
  - name: apecloud-mysql
    enabled: true
  - name: etcd
    enabled: true
  - name: influxdb
    enabled: true
  - name: kafka
    enabled: true
  - name: mariadb
    enabled: true
  - name: mongodb
    enabled: true
  - name: mysql
    enabled: true
  - name: nebula
    enabled: true
  - name: postgresql
    enabled: true
  - name: pulsar
    enabled: true
  - name: qdrant
    enabled: true
  - name: opensearch
    enabled: true
  - name: rabbitmq
    enabled: true
  - name: redis
    enabled: true
  - name: starrocks-ce
    enabled: true
  - name: tdengine
    enabled: true
  - name: tidb
    enabled: true
  - name: zookeeper
    enabled: true
