#!/usr/bin/env python3
"""
Download all Helm chart .tgz files from charts_v1.0.1.yaml generated by scrape_helm_charts.py
"""

import os
import yaml
import requests
from pathlib import Path
from typing import Dict, List
from urllib.parse import urlparse


def load_charts_yaml(yaml_file: str) -> Dict:
    """Load the charts YAML file"""
    try:
        with open(yaml_file, 'r') as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"Error loading YAML file: {e}")
        return {}


def extract_download_urls(charts_data: Dict, base_url: str = 'https://github.com/apecloud/helm-charts/releases/download/') -> List[Dict[str, str]]:
    """Extract all download URLs from charts data with mirror structure"""
    downloads = []

    for chart_name, versions in charts_data.items():
        for chart in versions:
            urls = chart.get('urls', [])
            version = chart.get('version', 'unknown')

            for url in urls:
                # Extract the relative path after the base URL
                relative_path = url.replace(base_url, '')

                downloads.append({
                    'chart_name': chart_name,
                    'version': version,
                    'url': url,
                    'relative_path': relative_path,
                    'filename': os.path.basename(urlparse(url).path)
                })

    return downloads


def download_file(url: str, output_path: str, chart_name: str, relative_path: str = None) -> bool:
    """Download a file from URL to output path"""
    try:
        display_path = relative_path if relative_path else output_path

        response = requests.get(url, stream=True, timeout=30)
        response.raise_for_status()

        # Get total file size if available
        total_size = int(response.headers.get('content-length', 0))

        # Download with progress
        downloaded = 0
        with open(output_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    downloaded += len(chunk)
                    if total_size > 0:
                        percent = (downloaded / total_size) * 100
                        print(f"  Progress: {percent:.1f}%", end='\r')

        print(f"  ✓ Downloaded: {display_path} ({downloaded} bytes)")
        return True

    except requests.RequestException as e:
        print(f"  ✗ Error downloading {chart_name}: {e}")
        return False
    except Exception as e:
        print(f"  ✗ Unexpected error: {e}")
        return False


def download_all_charts(yaml_file: str, output_dir: str = "helm-charts", base_url: str = 'https://github.com/apecloud/helm-charts/releases/download/'):
    """Download all charts from the YAML file with mirror directory structure"""

    # Create output directory
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    print(f"Output directory: {output_dir}")
    print(f"Mirror structure: Each chart in its own subdirectory\n")

    # Load charts data
    print(f"Loading charts from: {yaml_file}")
    charts_data = load_charts_yaml(yaml_file)

    if not charts_data:
        print("No charts data found")
        return

    # Extract download URLs
    downloads = extract_download_urls(charts_data, base_url)

    if not downloads:
        print("No download URLs found")
        return

    print(f"Found {len(downloads)} chart(s) to download\n")
    print("=" * 80)

    # Download each file
    success_count = 0
    failed_count = 0

    for idx, download in enumerate(downloads, 1):
        chart_name = download['chart_name']
        version = download['version']
        url = download['url']
        relative_path = download['relative_path']

        print(f"\n[{idx}/{len(downloads)}] {chart_name} v{version}")

        # Create full output path with subdirectory
        output_path = os.path.join(output_dir, relative_path)
        output_subdir = os.path.dirname(output_path)

        # Create subdirectory if it doesn't exist
        Path(output_subdir).mkdir(parents=True, exist_ok=True)

        # Skip if already exists
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path)
            print(f"  ⊙ Already exists: {relative_path} ({file_size} bytes)")
            success_count += 1
            continue

        # Download the file
        print(f"  Path: {relative_path}")
        if download_file(url, output_path, chart_name, relative_path):
            success_count += 1
        else:
            failed_count += 1

    # Summary
    print("\n" + "=" * 80)
    print(f"\nDownload Summary:")
    print(f"  Total: {len(downloads)}")
    print(f"  Success: {success_count}")
    print(f"  Failed: {failed_count}")
    print(f"\nAll charts saved to: {output_dir}/")
    print(f"\nMirror structure created:")
    print(f"  {output_dir}/")
    print(f"    ├── chart-name-1.0.1/")
    print(f"    │   └── chart-name-1.0.1.tgz")
    print(f"    └── ...")


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Download Helm chart .tgz files from charts YAML with mirror directory structure'
    )
    parser.add_argument(
        '-i', '--input',
        default='charts_v1.0.1.yaml',
        help='Input YAML file (default: charts_v1.0.1.yaml)'
    )
    parser.add_argument(
        '-o', '--output',
        default='helm-charts',
        help='Output directory (default: helm-charts)'
    )
    parser.add_argument(
        '-b', '--base-url',
        default='https://github.com/apecloud/helm-charts/releases/download/',
        help='Base URL to strip from chart URLs (default: https://github.com/apecloud/helm-charts/releases/download/)'
    )

    args = parser.parse_args()

    download_all_charts(args.input, args.output, args.base_url)


if __name__ == "__main__":
    main()
