#!/bin/bash -e
# process images.txt generated by extract_helm_images.py
while read image; do
    echo "Processing: $image"
    docker pull "$image"

    # Extract image name without registry
    image_name=$(echo "$image" | sed 's|.*/||')

    # Tag for target registry
    target_image="enexis-docker-480-local.jfrog.io/apecloud/$image_name"
    docker tag "$image" "$target_image"

    # Push to target registry

    echo "Completed: $target_image"
done < images.txt

docker images --format "{{.Repository}}:{{.Tag}}" | grep enexis |grep apecloud | xargs -n 1 docker push
