---

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  no_log: true  # too verbose

- name: "State variables - {{ desired_state }}"
  ansible.builtin.include_vars: "{{ desired_state }}.yml"

- name: "Converge state - {{ desired_state }}"
  ansible.builtin.include_tasks: "{{ desired_state }}.yml"

- name: Verify kbcli
  ansible.builtin.include_tasks: "verify.yml"
