---
# Tasks to reach desired state present with role opensearch

- name: Validate deployment environment
  ansible.builtin.fail:
    msg: "Invalid environment '{{ deployment_environment }}'. Valid options are: {{ opensearch_environments.keys() | list | join(', ') }}"
  when: deployment_environment not in opensearch_environments.keys()

- name: Prepare templates for opensearch-operator cluster
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ playbook_dir }}/files/{{ item }}"
    mode: '0600'
  loop:
    - opensearch-admin-credentials.yml
    - opensearch-dashboards-credentials.yml
    - opensearch-security-config.yml
    - opensearch-cluster.yml
    - opensearch-nodeport.yml

- name: Create OpenSearch cluster
  kubernetes.core.k8s:
    state: present
    namespace: logging
    definition: "{{ lookup('file', playbook_dir + '/files/{{ item }}') | from_yaml }}"
    validate:
      fail_on_error: true
    wait: true
    wait_timeout: 600
  loop:
    - opensearch-admin-credentials.yml
    - opensearch-dashboards-credentials.yml
    - opensearch-security-config.yml
    - opensearch-cluster.yml
    - opensearch-nodeport.yml
